# dbt_commands.tcl -- Innovus command wrappers for buffer-tree work.
#
# This file intentionally stays close to documented Innovus commands:
#   deleteBufferTree, ecoAddRepeater, ecoDeleteRepeater, addRepeaterByRule.
# Source this inside an initialized Innovus session.

namespace eval ::dbt {
    variable version 0.1
}

proc ::dbt::_bool {v} {
    return [expr {$v in {1 true yes on}}]
}

proc ::dbt::_quote_cmd {cmd} {
    set out {}
    foreach x $cmd {
        lappend out [list $x]
    }
    return [join $out " "]
}

proc ::dbt::_require_value {argv i opt} {
    if {$i >= [llength $argv]} {
        error "$opt requires a value"
    }
}

proc ::dbt::delete_buffer_tree_cmd {args} {
    set cmd [list deleteBufferTree]
    set i 0
    while {$i < [llength $args]} {
        set a [lindex $args $i]
        switch -- $a {
            -nets - -net {
                incr i
                ::dbt::_require_value $args $i $a
                lappend cmd -net [lindex $args $i]
            }
            -selNetFile - -net_file {
                incr i
                ::dbt::_require_value $args $i $a
                lappend cmd -selNetFile [lindex $args $i]
            }
            -excNetFile - -exclude_net_file {
                incr i
                ::dbt::_require_value $args $i $a
                lappend cmd -excNetFile [lindex $args $i]
            }
            -footprint {
                incr i
                ::dbt::_require_value $args $i $a
                lappend cmd -footprint [lindex $args $i]
            }
            -preserveRoute - -preserve_route {
                lappend cmd -preserveRoute
            }
            -verbose {
                lappend cmd -verbose
            }
            -help {
                lappend cmd -help
            }
            default {
                error "unknown delete_buffer_tree_cmd option '$a'"
            }
        }
        incr i
    }
    return $cmd
}

proc ::dbt::delete_buffer_tree {args} {
    set log ""
    set pass {}
    set i 0
    while {$i < [llength $args]} {
        set a [lindex $args $i]
        if {$a eq "-log"} {
            incr i
            ::dbt::_require_value $args $i $a
            set log [lindex $args $i]
        } else {
            lappend pass $a
        }
        incr i
    }

    set cmd [::dbt::delete_buffer_tree_cmd {*}$pass]
    if {$log ne ""} {
        set script [::dbt::_quote_cmd $cmd]
        return [uplevel #0 [list redirect $log $script]]
    }
    return [uplevel #0 $cmd]
}

proc ::dbt::write_delete_buffer_tree_script {out_file args} {
    set pre_def ""
    set post_def ""
    set log ""
    set include_unplaced 1
    set pass {}

    set i 0
    while {$i < [llength $args]} {
        set a [lindex $args $i]
        switch -- $a {
            -pre_def {
                incr i
                ::dbt::_require_value $args $i $a
                set pre_def [lindex $args $i]
            }
            -post_def {
                incr i
                ::dbt::_require_value $args $i $a
                set post_def [lindex $args $i]
            }
            -log {
                incr i
                ::dbt::_require_value $args $i $a
                set log [lindex $args $i]
            }
            -include_unplaced {
                incr i
                ::dbt::_require_value $args $i $a
                set include_unplaced [::dbt::_bool [lindex $args $i]]
            }
            default {
                lappend pass $a
            }
        }
        incr i
    }

    set cmd [::dbt::delete_buffer_tree_cmd {*}$pass]
    set flags [list -floorplan -netlist -routing]
    if {$include_unplaced} {
        lappend flags -unplaced
    }

    file mkdir [file dirname [file normalize $out_file]]
    set fp [open $out_file w]
    puts $fp "# Auto-generated by dbt::write_delete_buffer_tree_script"
    puts $fp "# Source/run inside an initialized Innovus session."
    if {$pre_def ne ""} {
        puts $fp "[::dbt::_quote_cmd [concat [list defOut] $flags [list $pre_def]]]"
    }
    if {$log ne ""} {
        puts $fp "[list redirect $log [::dbt::_quote_cmd $cmd]]"
    } else {
        puts $fp "[::dbt::_quote_cmd $cmd]"
    }
    if {$post_def ne ""} {
        puts $fp "[::dbt::_quote_cmd [concat [list defOut] $flags [list $post_def]]]"
    }
    close $fp
    return $out_file
}

proc ::dbt::eco_insert_repeater {args} {
    set cmd [list ecoAddRepeater]
    set single_inverter 0

    set i 0
    while {$i < [llength $args]} {
        set a [lindex $args $i]
        switch -- $a {
            -net {
                incr i
                ::dbt::_require_value $args $i $a
                lappend cmd -net [lindex $args $i]
            }
            -terms - -term {
                incr i
                ::dbt::_require_value $args $i $a
                lappend cmd -term [lindex $args $i]
            }
            -cell {
                incr i
                ::dbt::_require_value $args $i $a
                lappend cmd -cell [lindex $args $i]
            }
            -name {
                incr i
                ::dbt::_require_value $args $i $a
                lappend cmd -name [lindex $args $i]
            }
            -newNetName - -new_net_name {
                incr i
                ::dbt::_require_value $args $i $a
                lappend cmd -newNetName [lindex $args $i]
            }
            -loc {
                incr i
                ::dbt::_require_value $args $i $a
                lappend cmd -loc [lindex $args $i]
            }
            -relativeDistToSink - -relative_dist_to_sink {
                incr i
                ::dbt::_require_value $args $i $a
                lappend cmd -relativeDistToSink [lindex $args $i]
            }
            -offLoadSlack - -offload_slack {
                incr i
                ::dbt::_require_value $args $i $a
                lappend cmd -offLoadSlack [lindex $args $i]
            }
            -noPlace - -no_place {
                lappend cmd -noPlace
            }
            -single_inverter {
                incr i
                ::dbt::_require_value $args $i $a
                set single_inverter [::dbt::_bool [lindex $args $i]]
            }
            default {
                error "unknown eco_insert_repeater option '$a'"
            }
        }
        incr i
    }

    if {$single_inverter} {
        # Innovus default LEQ behavior inserts an inverter pair when the master
        # cell is an inverter. DBT compensation needs one inverter, so disable
        # that check for this call's session unless the caller overrides later.
        uplevel #0 [list setEcoMode -LEQCheck false]
    }
    return [uplevel #0 $cmd]
}

proc ::dbt::eco_delete_repeater {args} {
    set insts ""
    set inv_pairs ""
    set logical_only 0

    set i 0
    while {$i < [llength $args]} {
        set a [lindex $args $i]
        switch -- $a {
            -insts - -inst {
                incr i
                ::dbt::_require_value $args $i $a
                set insts [lindex $args $i]
            }
            -invPair - -inv_pair {
                incr i
                ::dbt::_require_value $args $i $a
                set inv_pairs [lindex $args $i]
            }
            -logicalChangeOnly - -logical_only {
                set logical_only 1
            }
            default {
                error "unknown eco_delete_repeater option '$a'"
            }
        }
        incr i
    }

    set cmd [list ecoDeleteRepeater]
    if {$logical_only} {
        lappend cmd -logicalChangeOnly
    }
    if {$insts ne ""} {
        lappend cmd -inst $insts
    } elseif {$inv_pairs ne ""} {
        lappend cmd -invPair $inv_pairs
    } else {
        error "eco_delete_repeater needs -insts or -inv_pair"
    }
    return [uplevel #0 $cmd]
}

proc ::dbt::add_repeater_by_rule {args} {
    set cmd [list addRepeaterByRule]
    set i 0
    while {$i < [llength $args]} {
        set a [lindex $args $i]
        switch -- $a {
            -rule {
                incr i
                ::dbt::_require_value $args $i $a
                lappend cmd -rule [lindex $args $i]
            }
            -nets {
                incr i
                ::dbt::_require_value $args $i $a
                lappend cmd -nets [lindex $args $i]
            }
            -selNet - -sel_net_file {
                incr i
                ::dbt::_require_value $args $i $a
                lappend cmd -selNet [lindex $args $i]
            }
            -excNet - -exclude_net_file {
                incr i
                ::dbt::_require_value $args $i $a
                lappend cmd -excNet [lindex $args $i]
            }
            -netMapping - -net_mapping {
                incr i
                ::dbt::_require_value $args $i $a
                lappend cmd -netMapping [lindex $args $i]
            }
            -outDir - -out_dir {
                incr i
                ::dbt::_require_value $args $i $a
                lappend cmd -outDir [lindex $args $i]
            }
            -preRoute - -pre_route {
                lappend cmd -preRoute
            }
            -postRoute - -post_route {
                lappend cmd -postRoute
            }
            -alongRoute - -along_route {
                lappend cmd -alongRoute
            }
            -copyNetAttribute - -copy_net_attribute {
                lappend cmd -copyNetAttribute
            }
            -allowMixedSignal - -allow_mixed_signal {
                lappend cmd -allowMixedSignal
            }
            default {
                error "unknown add_repeater_by_rule option '$a'"
            }
        }
        incr i
    }
    return [uplevel #0 $cmd]
}
